== Module 4: Managing SELinux permissions

=== What we will learn

In this module, we introduce the second of our rhel-system-roles used for security.

You will use the selinux role to:

* define allowed ports to be accessed under selinux
* define locations where web pages can be served from by a service

=== Background

David the web developer needs to have his website files be located in his home folder instead of the default apache location to properly manage his work.

We have tested his account and the correct permissions seem to be there, but we still can't access the site.

To fix this we will need to make sure the selinux rules are in place.

Lets check to see the permissions on his directory

[source,bash,run]
----
ls -lh /home/davidj/public_html
----

David owns the files, but others should be able to read them.
Lets see if we can access the web site.

[source,bash,run]
----
curl http://localhost:1337
----

Next lets make sure we have the selinux context set on the file.

[source,bash,run]
----
ls -Z /home/davidj/public_html
----

The context seems to be correct.
----
unconfined_u:object_r:httpd_sys_content_t:s0 
----

Lets exit david's account and try to remediate this.

[source,bash,run]
----
exit
----

David needs to access the web service on an uncommon port 1337.
We will use the SELinux system role set the permissions to allow port 1337 and make sure the right selinux file context is on the files.
We have a playbook we can use.

[source,bash,run]
----
cat /home/rhel/selinux.yml
----

=== What does this playbook do?

The playbook file is selinux.yml
The goal of the playbook is to ensure the correct SELinux policy on David's environment.

==== Hosts 

* localhost - it is targeted at the local computer

==== Variables

* *selinux_ports*: This sets up rules for SELinux (a security system) to allow traffic on port 1337 using the TCP protocol.
* *selinux_fcontexts*: This sets up file context rules for SELinux. It says that the directory `+/home/davidj/public_html+` should have the type `+httpd_sys_content_t+`.

==== Roles

* *rhel-system-roles.selinux*: This role sets up SELinux rules.

Run the playbook.

[source,bash,run]
----
ansible-playbook -i hosts.ini selinux.yml
----

Since we have made changes to the http service, we need to do is to restart the http service

[source,bash,run]
----
systemctl restart httpd
----

Now that ansible has made changes let's see if we can access the site

[source,bash,run]
----
curl http://localhost:1337
----

Awesome, we now see the index page returned.
Next, take a look at the permissions.

[source,bash,run]
----
semanage port -l | grep 1337
----

David's port is listed as allowed for serving web services.

[source,bash,run]
----
ls -Z /home/davidj/public_html
----

The web pages folder in David's home has the proper SELinux context do allow serving web pages.

We can now move on to the next section.
