== Module 6: Configure execution allow-lists with fapolicyd

=== What we will learn

In this module we will enforce allow list for applications running on our nodes.
This ensures that unauthorized executables are not able to launch.

We will:

* install fapolicyd binaries
* configure fapolicyd integrity checks
* configure trusted sources 
* configure specific trusted files

=== What does this playbook do?

Now lets look at a basic Fapolicyd playbook, where we want to install and enable the service to run.

[source,bash,run]
----
cat /home/rhel/fapolicyd.yml
----

The playbook is named "`Fapolicyd role invocation.`" 
This becomes a logging identifier to help you track what the playbook has been executed.

==== Hosts

The playbook is meant to run on all the host that are passed by the inventory.

==== Variables

Here are the variables:

* `+fapolicyd_setup_enable_service: true+`: This tells the playbook to enable the `+fapolicyd+` service.
* `+fapolicyd_setup_integrity: sha256+`: This sets the method to check the integrity of files to `+sha256+`, which is a way to make sure files haven’t been changed.
* `+fapolicyd_setup_trust: rpmdb,file+`: This tells the playbook to trust files from the RPM database and regular files.
* `+fapolicyd_add_trusted_file+`: This is a list of files that the playbook should trust. In this case, it includes `+/etc/passwd+`,
`+/etc/fapolicyd/fapolicyd.conf+`, and `+/etc/krb5.conf+`.

==== Roles

The playbook applies the role called `+rhel-system-roles.fapolicyd+` to hosts using the provided variables.
This role is specifically for setting up and managing the `+fapolicyd+` service.

Now lets run it with ansible

[source,bash,run]
----
ansible-playbook -i /home/rhel/hosts.ini /home/rhel/fapolicyd.yml
----

As you can see following the execution of the role, it takes into consideration all the checks and validations that need to occur to run fapolicyd correctly on a host. 

When complete our system will only allow our trusted software to run on the hosts.

SUCCESS!

