== Module 7: The Basic Security Automation playbook

=== What we will learn

In this module we will pull all the configuration together into a single playbook.


=== Lets put all the separate roles together

Once you have your settings pushed with ansible, and you want to put them all into one playbook, it would look something like this!

[source,bash,run]
----
cat bsa.yml
----

=== What Does This Playbook Do?

==== Title and Targets

* *Name*: The playbook is named "`Example Basic Security Automation (BSA) system roles.`"
* *Hosts*: It will run on all the computers (hosts) that Ansible is managing.

==== Variables

* *sudo_rules*: This tells the computer which users can run certain commands without needing a password. In this case, the user "`audit-sa`" can run the command `+/usr/sbin/aide+` without a password.
* *selinux_ports*: This sets up rules for SELinux (a security system) to allow traffic on port 1337 using the TCP protocol.
* *selinux_fcontexts*: This sets up file context rules for SELinux. It says that the directory `+/home/davidj/public_html+` should have the type `+httpd_sys_content_t+`.
* *aide_db_fetch_dir*: This tells where to fetch the AIDE (Advanced Intrusion Detection Environment) database from.
* *aide_install, aide_generate_config, aide_init, aide_check, aide_update*: These are settings for AIDE. It tells the computer to install AIDE, generate its  configuration, initialize it, but not to check or update it.
* *fapolicyd_setup_enable_service, fapolicyd_setup_integrity, fapolicyd_setup_trust, fapolicyd_add_trusted_file*: These are settings for `+fapolicyd+`, a file access policy daemon. It tells the computer to enable the service, use SHA256 for integrity checks, trust certain files, and add specific files to the trusted list.

==== Roles

* *rhel-system-roles.sudo*: This role sets up sudo rules.
* *rhel-system-roles.selinux*: This role sets up SELinux rules.
* *rhel-system-roles.aide*: This role sets up AIDE for file integrity checking.
* *rhel-system-roles.fapolicyd*: This role sets up `+fapolicyd+` for file access policies.

=== What does the bsa.yml playbook address?

* *Security*: The playbook is designed to increase the overall security of our system.
* *Permissions*: It controls which users can elevate their privilege, what privileges can be elevated and the required authentication.
* *File Access*: By enforcing mandatory access control through SELinux, it ensures appropriate object access within RHEL.
* *File Integrity*: It maintains file signatures and checks if files have been changed unexpectedly.
* *Network Security*: It controls which network ports can be used.

Our playbook automates a significant set of tasks and allows to build more secure systems quickly and easily. 
This is a huge time saver and allows us to deliver validated systems faster!

==== Run the playbook.

[source,bash,run]
----
ansible-playbook -i hosts.ini bsa.yml
----

== Conclusion

In this lab you learned the following:

* the basics of running ansible securely
* how create users and groups securely
* assing and manage permissions and local sudo rules
* modify SELinux permissions and context
* configure system integrity with aide
* define an allow list of permitted applications using fapolicyd
* define a basic security automation policy in a playbook

The rhel_system_roles provide for even more security configuration including:

* configuring firewalld settings
* configuring terminal logging through tlog
* configuring log settings and forwarding
* configuring system-wide cryptographic policy
* binding encrypted volumes to networks and trusted platform modules
* creating and renewing certificates
* configuring VPN
* configuring sshd
* configuring Active Directory Integration
* AND More

Red Hat also provides the redhat.rhel_idm collection for managing centralized policy through Red Hat Identity Management.

Review our complete ducumentation for details.

Thanks for your participation!

=== Resources

If you want to learn more about RHEL System Roles, you can check out our documentation.
https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/automating_system_administration_by_using_rhel_system_roles/intro-to-rhel-system-roles_automating-system-administration-by-using-rhel-system-roles

Reach out to your Red Hat Team for more labs on Red Hat Enterprise Linux!
